_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  actions_permissions: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cas: 0
  cas_attributes: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_ignore: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  disable_field: 0
  dynamic_page_cache: 0
  editor: 0
  entity_clone: 0
  entity_reference_revisions: 0
  feed_title_lock: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  json_feed: 0
  jsonapi: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  rest: 0
  rh_node: 0
  scheduler: 0
  scroll_fix: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  typed_data: 0
  ultimate_cron: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_field_view: 0
  views_ical: 0
  views_ui: 0
  workbench_access: 0
  workflows: 0
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  usf_events: 0
  claro: 0
profile: standard
